SEED: 7

DATA:
  PIN_MEMORY: False
MODEL:
  NAME: test
TRAIN:
  DEVICE: "cpu"
  NUM_ITERATIONS: 100
  WARMUP_ITERATIONS: 10
  BASE_LR: 1.0e-4
  WARMUP_LR: 1.0e-5
  CHECKPOINT_EVERY: -1
LOGGING:
  LOG_EVERY: 1


TAG: test_model